2021-07-17 14:04:53,300 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/views.py changed, reloading.
2021-07-17 14:04:53,301 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:04:59,350 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/views.py changed, reloading.
2021-07-17 14:04:59,351 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:05:07,483 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/views.py changed, reloading.
2021-07-17 14:05:07,484 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:05:39,220 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/urls.py changed, reloading.
2021-07-17 14:05:39,221 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:05:54,352 django.request WARNING  Method Not Allowed: /api/casedel/5/
2021-07-17 14:05:59,413 django.request WARNING  Method Not Allowed: /api/casedel/5/
2021-07-17 14:06:17,203 django.request WARNING  Method Not Allowed: /api/casedel/5/
2021-07-17 14:07:21,585 django.request WARNING  Method Not Allowed: /api/casedel/5/
2021-07-17 14:07:30,113 django.request WARNING  Method Not Allowed: /api/casedel/5/
2021-07-17 14:09:09,699 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/views.py changed, reloading.
2021-07-17 14:09:09,700 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:09:16,403 django.request ERROR    Internal Server Error: /api/casedel/5/
Traceback (most recent call last):
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/hukewei33/medFlashCardDocker/flashCardApp/views.py", line 131, in caseDelete
    return Response(status=status.HTTP_204_NO_CONTENT)
NameError: name 'status' is not defined
2021-07-17 14:09:42,535 django.utils.autoreload INFO     /home/hukewei33/medFlashCardDocker/flashCardApp/views.py changed, reloading.
2021-07-17 14:09:42,537 asyncio      DEBUG    Using selector: EpollSelector
2021-07-17 14:09:47,017 django.request ERROR    Internal Server Error: /api/casedel/5/
Traceback (most recent call last):
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/hukewei33/medFlashCardDocker/flashCardApp/views.py", line 129, in caseDelete
    case = Case.objects.get(id=pk)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/hukewei33/.local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
flashCardApp.models.Case.DoesNotExist: Case matching query does not exist.
