2021-07-13 06:02:50,024 PIL.PngImagePlugin DEBUG    STREAM b'IHDR' 16 13
2021-07-13 06:02:50,024 PIL.PngImagePlugin DEBUG    STREAM b'sRGB' 41 1
2021-07-13 06:02:50,024 PIL.PngImagePlugin DEBUG    STREAM b'gAMA' 54 4
2021-07-13 06:02:50,025 PIL.PngImagePlugin DEBUG    STREAM b'pHYs' 70 9
2021-07-13 06:02:50,025 PIL.PngImagePlugin DEBUG    STREAM b'IDAT' 91 65445
2021-07-13 06:02:50,025 PIL.Image    DEBUG    Importing BlpImagePlugin
2021-07-13 06:02:50,026 PIL.Image    DEBUG    Importing BmpImagePlugin
2021-07-13 06:02:50,027 PIL.Image    DEBUG    Importing BufrStubImagePlugin
2021-07-13 06:02:50,027 PIL.Image    DEBUG    Importing CurImagePlugin
2021-07-13 06:02:50,028 PIL.Image    DEBUG    Importing DcxImagePlugin
2021-07-13 06:02:50,030 PIL.Image    DEBUG    Importing DdsImagePlugin
2021-07-13 06:02:50,030 PIL.Image    DEBUG    Importing EpsImagePlugin
2021-07-13 06:02:50,032 PIL.Image    DEBUG    Importing FitsStubImagePlugin
2021-07-13 06:02:50,034 PIL.Image    DEBUG    Importing FliImagePlugin
2021-07-13 06:02:50,035 PIL.Image    DEBUG    Importing FpxImagePlugin
2021-07-13 06:02:50,036 PIL.Image    DEBUG    Image: failed to import FpxImagePlugin: No module named 'olefile'
2021-07-13 06:02:50,036 PIL.Image    DEBUG    Importing FtexImagePlugin
2021-07-13 06:02:50,037 PIL.Image    DEBUG    Importing GbrImagePlugin
2021-07-13 06:02:50,037 PIL.Image    DEBUG    Importing GifImagePlugin
2021-07-13 06:02:50,038 PIL.Image    DEBUG    Importing GribStubImagePlugin
2021-07-13 06:02:50,038 PIL.Image    DEBUG    Importing Hdf5StubImagePlugin
2021-07-13 06:02:50,039 PIL.Image    DEBUG    Importing IcnsImagePlugin
2021-07-13 06:02:50,042 PIL.Image    DEBUG    Importing IcoImagePlugin
2021-07-13 06:02:50,043 PIL.Image    DEBUG    Importing ImImagePlugin
2021-07-13 06:02:50,045 PIL.Image    DEBUG    Importing ImtImagePlugin
2021-07-13 06:02:50,047 PIL.Image    DEBUG    Importing IptcImagePlugin
2021-07-13 06:02:50,049 PIL.Image    DEBUG    Importing JpegImagePlugin
2021-07-13 06:02:50,050 PIL.Image    DEBUG    Importing Jpeg2KImagePlugin
2021-07-13 06:02:50,050 PIL.Image    DEBUG    Importing McIdasImagePlugin
2021-07-13 06:02:50,051 PIL.Image    DEBUG    Importing MicImagePlugin
2021-07-13 06:02:50,053 PIL.Image    DEBUG    Image: failed to import MicImagePlugin: No module named 'olefile'
2021-07-13 06:02:50,053 PIL.Image    DEBUG    Importing MpegImagePlugin
2021-07-13 06:02:50,054 PIL.Image    DEBUG    Importing MpoImagePlugin
2021-07-13 06:02:50,055 PIL.Image    DEBUG    Importing MspImagePlugin
2021-07-13 06:02:50,056 PIL.Image    DEBUG    Importing PalmImagePlugin
2021-07-13 06:02:50,059 PIL.Image    DEBUG    Importing PcdImagePlugin
2021-07-13 06:02:50,060 PIL.Image    DEBUG    Importing PcxImagePlugin
2021-07-13 06:02:50,060 PIL.Image    DEBUG    Importing PdfImagePlugin
2021-07-13 06:02:50,074 PIL.Image    DEBUG    Importing PixarImagePlugin
2021-07-13 06:02:50,075 PIL.Image    DEBUG    Importing PngImagePlugin
2021-07-13 06:02:50,075 PIL.Image    DEBUG    Importing PpmImagePlugin
2021-07-13 06:02:50,075 PIL.Image    DEBUG    Importing PsdImagePlugin
2021-07-13 06:02:50,076 PIL.Image    DEBUG    Importing SgiImagePlugin
2021-07-13 06:02:50,077 PIL.Image    DEBUG    Importing SpiderImagePlugin
2021-07-13 06:02:50,078 PIL.Image    DEBUG    Importing SunImagePlugin
2021-07-13 06:02:50,079 PIL.Image    DEBUG    Importing TgaImagePlugin
2021-07-13 06:02:50,080 PIL.Image    DEBUG    Importing TiffImagePlugin
2021-07-13 06:02:50,080 PIL.Image    DEBUG    Importing WebPImagePlugin
2021-07-13 06:02:50,085 PIL.Image    DEBUG    Importing WmfImagePlugin
2021-07-13 06:02:50,088 PIL.Image    DEBUG    Importing XbmImagePlugin
2021-07-13 06:02:50,090 PIL.Image    DEBUG    Importing XpmImagePlugin
2021-07-13 06:02:50,092 PIL.Image    DEBUG    Importing XVThumbImagePlugin
2021-07-13 06:03:06,484 django.request WARNING  Not Found: /favicon.ico
2021-07-13 06:04:57,328 django.request WARNING  Not Found: /api/cases/
2021-07-13 13:54:41,604 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 13:55:13,915 django.request WARNING  Not Found: /favicon.ico
2021-07-13 13:55:14,163 django.request WARNING  Not Found: /favicon.ico
2021-07-13 13:55:53,973 django.request WARNING  Not Found: /api/cases/
2021-07-13 13:56:02,656 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 13:56:26,512 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 13:56:58,777 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 14:01:59,913 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 14:01:59,976 django.request ERROR    Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 221, in inner
    if not self.has_permission(request):
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/hukewei33/.local/share/virtualenvs/medFlashCardDocker-Fl-Js0Sw/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
2021-07-13 14:02:37,145 asyncio      DEBUG    Using selector: EpollSelector
2021-07-13 14:02:46,734 asyncio      DEBUG    Using selector: EpollSelector
